// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/v1/lot.proto

package lot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LotService_CreateLot_FullMethodName  = "/lot.LotService/CreateLot"
	LotService_GetLotByID_FullMethodName = "/lot.LotService/GetLotByID"
	LotService_ListLots_FullMethodName   = "/lot.LotService/ListLots"
)

// LotServiceClient is the client API for LotService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LotServiceClient interface {
	CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotResponse, error)
	GetLotByID(ctx context.Context, in *GetLotByIDRequest, opts ...grpc.CallOption) (*GetLotByIDResponse, error)
	ListLots(ctx context.Context, in *ListLotsRequest, opts ...grpc.CallOption) (*ListLotsResponse, error)
}

type lotServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLotServiceClient(cc grpc.ClientConnInterface) LotServiceClient {
	return &lotServiceClient{cc}
}

func (c *lotServiceClient) CreateLot(ctx context.Context, in *CreateLotRequest, opts ...grpc.CallOption) (*CreateLotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLotResponse)
	err := c.cc.Invoke(ctx, LotService_CreateLot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotServiceClient) GetLotByID(ctx context.Context, in *GetLotByIDRequest, opts ...grpc.CallOption) (*GetLotByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLotByIDResponse)
	err := c.cc.Invoke(ctx, LotService_GetLotByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotServiceClient) ListLots(ctx context.Context, in *ListLotsRequest, opts ...grpc.CallOption) (*ListLotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLotsResponse)
	err := c.cc.Invoke(ctx, LotService_ListLots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotServiceServer is the server API for LotService service.
// All implementations must embed UnimplementedLotServiceServer
// for forward compatibility.
type LotServiceServer interface {
	CreateLot(context.Context, *CreateLotRequest) (*CreateLotResponse, error)
	GetLotByID(context.Context, *GetLotByIDRequest) (*GetLotByIDResponse, error)
	ListLots(context.Context, *ListLotsRequest) (*ListLotsResponse, error)
	mustEmbedUnimplementedLotServiceServer()
}

// UnimplementedLotServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLotServiceServer struct{}

func (UnimplementedLotServiceServer) CreateLot(context.Context, *CreateLotRequest) (*CreateLotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLot not implemented")
}
func (UnimplementedLotServiceServer) GetLotByID(context.Context, *GetLotByIDRequest) (*GetLotByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLotByID not implemented")
}
func (UnimplementedLotServiceServer) ListLots(context.Context, *ListLotsRequest) (*ListLotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLots not implemented")
}
func (UnimplementedLotServiceServer) mustEmbedUnimplementedLotServiceServer() {}
func (UnimplementedLotServiceServer) testEmbeddedByValue()                    {}

// UnsafeLotServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LotServiceServer will
// result in compilation errors.
type UnsafeLotServiceServer interface {
	mustEmbedUnimplementedLotServiceServer()
}

func RegisterLotServiceServer(s grpc.ServiceRegistrar, srv LotServiceServer) {
	// If the following call pancis, it indicates UnimplementedLotServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LotService_ServiceDesc, srv)
}

func _LotService_CreateLot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotServiceServer).CreateLot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotService_CreateLot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotServiceServer).CreateLot(ctx, req.(*CreateLotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotService_GetLotByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLotByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotServiceServer).GetLotByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotService_GetLotByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotServiceServer).GetLotByID(ctx, req.(*GetLotByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LotService_ListLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotServiceServer).ListLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LotService_ListLots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotServiceServer).ListLots(ctx, req.(*ListLotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LotService_ServiceDesc is the grpc.ServiceDesc for LotService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LotService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lot.LotService",
	HandlerType: (*LotServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLot",
			Handler:    _LotService_CreateLot_Handler,
		},
		{
			MethodName: "GetLotByID",
			Handler:    _LotService_GetLotByID_Handler,
		},
		{
			MethodName: "ListLots",
			Handler:    _LotService_ListLots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/lot.proto",
}
