// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: proto/v1/auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Auction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LotId        int64   `protobuf:"varint,2,opt,name=lot_id,json=lotId,proto3" json:"lot_id,omitempty"`
	Status       string  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "OPEN", "CLOSED"
	WinnerId     int64   `protobuf:"varint,4,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	FinalPrice   float64 `protobuf:"fixed64,5,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	AuctionStart string  `protobuf:"bytes,6,opt,name=auction_start,json=auctionStart,proto3" json:"auction_start,omitempty"` // ISO8601 datetime format
	AuctionEnd   string  `protobuf:"bytes,7,opt,name=auction_end,json=auctionEnd,proto3" json:"auction_end,omitempty"`       // ISO8601 datetime format
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_proto_v1_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_proto_v1_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Auction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Auction) GetLotId() int64 {
	if x != nil {
		return x.LotId
	}
	return 0
}

func (x *Auction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Auction) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *Auction) GetFinalPrice() float64 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

func (x *Auction) GetAuctionStart() string {
	if x != nil {
		return x.AuctionStart
	}
	return ""
}

func (x *Auction) GetAuctionEnd() string {
	if x != nil {
		return x.AuctionEnd
	}
	return ""
}

type GetAuctionByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAuctionByIDRequest) Reset() {
	*x = GetAuctionByIDRequest{}
	mi := &file_proto_v1_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionByIDRequest) ProtoMessage() {}

func (x *GetAuctionByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auction_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuctionByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAuctionByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auction *Auction `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
}

func (x *GetAuctionByIDResponse) Reset() {
	*x = GetAuctionByIDResponse{}
	mi := &file_proto_v1_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionByIDResponse) ProtoMessage() {}

func (x *GetAuctionByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auction_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuctionByIDResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

type CloseAuctionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CloseAuctionRequest) Reset() {
	*x = CloseAuctionRequest{}
	mi := &file_proto_v1_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAuctionRequest) ProtoMessage() {}

func (x *CloseAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAuctionRequest.ProtoReflect.Descriptor instead.
func (*CloseAuctionRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auction_proto_rawDescGZIP(), []int{3}
}

func (x *CloseAuctionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CloseAuctionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auction *Auction `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
}

func (x *CloseAuctionResponse) Reset() {
	*x = CloseAuctionResponse{}
	mi := &file_proto_v1_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseAuctionResponse) ProtoMessage() {}

func (x *CloseAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseAuctionResponse.ProtoReflect.Descriptor instead.
func (*CloseAuctionResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auction_proto_rawDescGZIP(), []int{4}
}

func (x *CloseAuctionResponse) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

var File_proto_v1_auction_proto protoreflect.FileDescriptor

var file_proto_v1_auction_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xcc, 0x01, 0x0a, 0x07, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x69, 0x6e,
	0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a,
	0x66, 0x69, 0x6e, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64,
	0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x25, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x14, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x41,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a,
	0x0a, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xb0, 0x01, 0x0a, 0x0e, 0x41,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x1e, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4b, 0x0a, 0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x41, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a,
	0x16, 0x69, 0x6e, 0x64, 0x69, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_auction_proto_rawDescOnce sync.Once
	file_proto_v1_auction_proto_rawDescData = file_proto_v1_auction_proto_rawDesc
)

func file_proto_v1_auction_proto_rawDescGZIP() []byte {
	file_proto_v1_auction_proto_rawDescOnce.Do(func() {
		file_proto_v1_auction_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_auction_proto_rawDescData)
	})
	return file_proto_v1_auction_proto_rawDescData
}

var file_proto_v1_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_auction_proto_goTypes = []any{
	(*Auction)(nil),                // 0: auction.Auction
	(*GetAuctionByIDRequest)(nil),  // 1: auction.GetAuctionByIDRequest
	(*GetAuctionByIDResponse)(nil), // 2: auction.GetAuctionByIDResponse
	(*CloseAuctionRequest)(nil),    // 3: auction.CloseAuctionRequest
	(*CloseAuctionResponse)(nil),   // 4: auction.CloseAuctionResponse
}
var file_proto_v1_auction_proto_depIdxs = []int32{
	0, // 0: auction.GetAuctionByIDResponse.auction:type_name -> auction.Auction
	0, // 1: auction.CloseAuctionResponse.auction:type_name -> auction.Auction
	1, // 2: auction.AuctionService.GetAuctionByID:input_type -> auction.GetAuctionByIDRequest
	3, // 3: auction.AuctionService.CloseAuction:input_type -> auction.CloseAuctionRequest
	2, // 4: auction.AuctionService.GetAuctionByID:output_type -> auction.GetAuctionByIDResponse
	4, // 5: auction.AuctionService.CloseAuction:output_type -> auction.CloseAuctionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_auction_proto_init() }
func file_proto_v1_auction_proto_init() {
	if File_proto_v1_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_auction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_auction_proto_goTypes,
		DependencyIndexes: file_proto_v1_auction_proto_depIdxs,
		MessageInfos:      file_proto_v1_auction_proto_msgTypes,
	}.Build()
	File_proto_v1_auction_proto = out.File
	file_proto_v1_auction_proto_rawDesc = nil
	file_proto_v1_auction_proto_goTypes = nil
	file_proto_v1_auction_proto_depIdxs = nil
}
